Man10Big:
  prefix: §f§l[§d§lMan10§f§lビッグ§a§l宝くじ§f§l]
  dispName: まん１０ビッグ
  lore:
  - テキスト１
  - テキスト２
  price: 10000
  prize: 500000000
  stock: 5000
  max_chance: 100000
  current_stock: 0.0
  count: 0
  win: 0
  command:
Man10:
  prefix: §f§l[§d§lMan10§f§lミニ§a§l宝くじ§f§l]
  dispName: まん１０くじ
  lore:
  - テキスト１
  - テキスト２
  price: 1000
  prize: 50000000
  stock: 500
  max_chance: 10000
  current_stock: 0.0
  count: 0
  win: 0
  command:
Man10Mini:
  prefix: §f§l[§d§lMan10§f§lミニ§a§l宝くじ§f§l]
  dispName: まん１０ミニ
  lore:
  - テキスト１
  - テキスト２
  price: 100
  prize: 5000000
  stock: 50
  max_chance: 1000
  current_stock: 0.0
  count: 0
  win: 0
  command:
Man10Nano:
  prefix: §f§l[§d§lMan10§f§lナノ§a§l宝くじ§f§l]
  dispName: まん１０ナノ
  lore:
  - テキスト１
  - テキスト２
  price: 10
  prize: 50000
  stock: 5
  max_chance: 100
  current_stock: 0.0
  count: 0
  win: 0
  command:

