Man10Big:
  prefix: '§f§l[§d§lMan10§f§lビッグ§a§l宝くじ§f§l]'
  dispName: '§f§lまん１０§4§lビッグ'
  lore:
  - '§f１枚10000円の宝くじ 大当たり５億円＋ストック'
  - 'クリックすると使えます'
  price: 10000
  prize: 500000000
  stock: 5000
  max_chance: 100000
  current_stock: 0.0
  count: 0
  win: 0
  command:
Man10:
  prefix: '§f§l[§d§lMan10§f§lミニ§a§l宝くじ§f§l]'
  dispName: '§d§lまん§f§l１０§a§lくじ'
  lore:
  - '§f１枚1000円の宝くじ 大当たり5000万円＋ストック'
  - 'クリックすると使えます'
  price: 1000
  prize: 50000000
  stock: 500
  max_chance: 10000
  current_stock: 0.0
  count: 0
  win: 0
  command:
Man10Mini:
  prefix: '§f§l[§d§lMan10§f§lミニ§a§l宝くじ§f§l]'
  dispName: '§f§lまん１０§5§lミニ'
  lore:
  - '§f１枚100円の宝くじ 大当たり500万円＋ストック'
  - 'クリックすると使えます'
  price: 100
  prize: 5000000
  stock: 50
  max_chance: 1000
  current_stock: 0.0
  count: 0
  win: 0
  command:
Man10Nano:
  prefix: '§f§l[§d§lMan10§f§lナノ§a§l宝くじ§f§l]'
  dispName: '§f§lまん１０§b§lナノ'
  lore:
  - '&f１枚10円の宝くじ 大当たり5万円＋ストック'
  - 'クリックすると使えます'
  price: 10
  prize: 50000
  stock: 5
  max_chance: 100000
  current_stock: 0.0
  count: 0
  win: 0
  command:
